[package]
name = "ztl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.19"
crossterm = { path = "../crossterm" }
color-eyre = "0.6.2"
ropey = "1.6.0"
